<a href="https://colab.research.google.com/github/Esbern/Python-for-Planners/blob/main/basic_python/00a_Random_numbers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Generating random numbers in Python can be done in several ways, depending on your specific needs:



### 1. The Built-in `random` Module

For many everyday tasks, Python’s built-in `random` module is sufficient. It offers functions such as:

- **`random.random()`**: Returns a random float in the range [0.0, 1.0).
- **`random.randint(a, b)`**: Returns a random integer N such that a ≤ N ≤ b.
- **`random.choice(sequence)`**: Randomly selects an item from a non-empty sequence.



In [5]:

import random

# Random float between 0 and 1
print(random.random())

# Random integer between 1 and 10
print(random.randint(1, 10))

# Random selection from a list
fruits = ['apple', 'banana', 'cherry']
print(random.choice(fruits))


0.17258613134835643
7
banana


### 2. The `numpy.random` Module

For simulation tasks and handling large datasets—common in urban planning and digital twins—the `numpy.random` module is very powerful and efficient. It can generate arrays of random numbers and offers a variety of distributions.



In [6]:

import numpy as np

# Array of 5 random floats between 0 and 1
print(np.random.rand(5))

# Array of 5 random integers between 1 and 10
print(np.random.randint(1, 10, size=5))


[0.96286125 0.91779701 0.97066311 0.98847476 0.05168793]
[3 9 8 3 6]


### 3. Seeding for Reproducibility

Both modules allow you to set a seed, which is essential if you need reproducible results for simulations.



In [11]:

import random
random.seed(42)
print(random.random())

import numpy as np
np.random.seed(42)
print(np.random.rand(5))


0.6394267984578837
[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]


### 4. Cryptographically Secure Random Numbers

If your application requires secure random numbers (less common in simulation), consider using the `secrets` module, which is designed for cryptographic purposes.



In [ ]:

import secrets

# Generate a secure random number between 0 and 100
print(secrets.randbelow(101))


### Conclusion

For your workshop focused on simulation and urban digital twins:

- **Use the built-in `random` module** for simple tasks and quick experiments.
- **Leverage `numpy.random`** for simulations requiring high-performance array computations and more complex random number generation.
- **Remember to seed your generators** if you need consistent, repeatable outcomes.

Each approach serves different purposes, so choose the one that best fits your simulation requirements and performance needs.